### ISSUE TITLE
redmine problem 1.4.x:

### ISSUE THREAD

**Issue by zodman** [altsol/redmine_mattermost#3]
```
Processing SettingsController#plugin (for 10.0.0.2 at 2016-01-20 16:42:28) [POST]
  Parameters: {"commit"=>"Apply", "action"=>"plugin", "authenticity_token"=>"ATClq/efld1Ej/AmyEKL0lcSJrgiIxQr35eSxXJBCrU=", "settings"=>{"post_updates"=>"1", "display_watchers"=>"yes", "username"=>"redmine", "icon"=>"https://raw.githubusercontent.com/altsol/redmine_mattermost/assets/icon.png", "channel"=>"redmine", "mattermost_url"=>"https://mattermost.interalia.net/hooks/hiqgxjqadpb1djm4emi1scfn8a"}, "controller"=>"settings"}

NoMethodError (undefined method `to_sym' for nil:NilClass):
  lib/redmine/plugin.rb:84:in `find'
  app/controllers/settings_controller.rb:52:in `plugin'
  /usr/lib/ruby/1.8/action_controller/base.rb:1331:in `send'
  /usr/lib/ruby/1.8/action_controller/base.rb:1331:in `perform_action_without_filters'
  /usr/lib/ruby/1.8/action_controller/filters.rb:617:in `call_filters'
  /usr/lib/ruby/1.8/action_controller/filters.rb:610:in `perform_action_without_benchmark'
  /usr/lib/ruby/1.8/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
  /usr/lib/ruby/1.8/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
  /usr/lib/ruby/1.8/action_controller/rescue.rb:160:in `perform_action_without_flash'
  /usr/lib/ruby/1.8/action_controller/flash.rb:146:in `perform_action'
  /usr/lib/ruby/1.8/action_controller/base.rb:532:in `send'
  /usr/lib/ruby/1.8/action_controller/base.rb:532:in `process_without_filters'
  /usr/lib/ruby/1.8/action_controller/filters.rb:606:in `process'
  /usr/lib/ruby/1.8/action_controller/base.rb:391:in `process'
  /usr/lib/ruby/1.8/action_controller/base.rb:386:in `call'
  /usr/lib/ruby/1.8/action_controller/routing/route_set.rb:437:in `call'
  /usr/lib/ruby/1.8/action_controller/dispatcher.rb:87:in `dispatch'
  /usr/lib/ruby/1.8/action_controller/dispatcher.rb:121:in `_call'
  /usr/lib/ruby/1.8/action_controller/dispatcher.rb:130:in `build_middleware_stack'
  /usr/lib/ruby/1.8/active_record/query_cache.rb:29:in `call'
  /usr/lib/ruby/1.8/active_record/query_cache.rb:29:in `call'
  /usr/lib/ruby/1.8/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
  /usr/lib/ruby/1.8/active_record/query_cache.rb:9:in `cache'
  /usr/lib/ruby/1.8/active_record/query_cache.rb:28:in `call'
  /usr/lib/ruby/1.8/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
  /usr/lib/ruby/1.8/action_controller/string_coercion.rb:25:in `call'
  /usr/lib/ruby/1.8/rack/head.rb:9:in `call'
  /usr/lib/ruby/1.8/rack/methodoverride.rb:24:in `call'
  /usr/lib/ruby/1.8/action_controller/params_parser.rb:15:in `call'
  /usr/lib/ruby/1.8/action_controller/session/cookie_store.rb:93:in `call'
  /usr/lib/ruby/1.8/action_controller/failsafe.rb:26:in `call'
  /usr/lib/ruby/1.8/rack/lock.rb:11:in `call'
  /usr/lib/ruby/1.8/rack/lock.rb:11:in `synchronize'
  /usr/lib/ruby/1.8/rack/lock.rb:11:in `call'
  /usr/lib/ruby/1.8/action_controller/dispatcher.rb:106:in `call'
  /usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:92:in `process_request'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:418:in `start_request_handler'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:358:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/utils.rb:184:in `safe_fork'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:354:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:163:in `start'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:213:in `start'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  /usr/lib/phusion_passenger/passenger-spawn-server:61


Rendering /usr/share/redmine/public/500.html (500 Internal Server Error)
```

**Comment by thanosk** [comment]
Hi @zodman this plugin as is supports Redmine versions 2.x up to 3.1.x (still haven't tested on Redmine 3.2.x). Unfortunately, adding support for older versions of Redmine is not in my current plans. If you are able to get it working however, pull requests are gladly welcome!

**Comment by zodman** [comment]
help me dude i need 

https://github.com/altsol/redmine_mattermost/blob/master/lib/redmine_mattermost/listener.rb#L130

This line to support redmine 1.4.x 

NoMethodError (undefined method `application' for Rails:Module):

i dont find the solving on google and my ruby expertise its bad!

**Comment by thanosk** [comment]
@zodman that lines uses Rails 3.0 version [Rails::Application](http://api.rubyonrails.org/classes/Rails/Application.html) object. I doubt you can use that version of Rails to run Redmine 1.4.x. You really should consider updating you redmine installation to a more recent version.
